name: crm-application
services:
- name: backend
  source_dir: /backend
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
  run_command: python app.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  routes:
  - path: /api
  envs:
  - key: FLASK_ENV
    value: production
  - key: DB_HOST
    value: ${db.HOSTNAME}
  - key: DB_USER
    value: ${db.USERNAME}
  - key: DB_PASSWORD
    value: ${db.PASSWORD}
  - key: DB_NAME
    value: ${db.DATABASE}
  - key: JWT_SECRET_KEY
    value: ${JWT_SECRET_KEY}
    type: SECRET

- name: frontend
  source_dir: /frontend
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
  build_command: npm ci && npm run build
  run_command: npx serve -s build -l 3000
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    value: https://backend-${APP_ID}.ondigitalocean.app

databases:
- name: db
  engine: MYSQL
  version: "8"
  size: db-s-dev-database
  num_nodes: 1
